spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      #      username:
      #      password:
      auto-index-creation: true

server:
  port: 8082
  servlet:
    context-path: /journal

logging:
  level:
    com:
      engineering:
        journalApp: ERROR

weather:
  api:
    key: aa64476ba28de3e85749789ad34830cd
