spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
#      username:
#      password:
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal